/* Import of React and ReactDOM module for rendering of main component */
import React from 'react';
import ReactDOM from 'react-dom/client';

/* Import of main component */
import { App } from './App';

/* Import of BrowserRouter module needed for the use of React-Router in the app */
import { BrowserRouter } from "react-router-dom";

/* Import of main stylesheet generated by SCSS files and preprocessor */
import './scss/main.css';

/* Import of the reportWebVitals module to enable performance measurement (see below) */
import reportWebVitals from './reportWebVitals';

/* Render of the main component into the div with id "root" in the index.html file. The setup for the
* React strict mode as well as the BrowserRouter is also handled here */
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <App/>
        </BrowserRouter>
    </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
