/* Import of main stylesheet generated by SCSS files and preprocessor */
import '../scss/main.css';

/* The "car card" components used in the CarView component to display car information */
export const CarCard = ({id, make, model, seats, image}) => {

    /* The rendering of the car details using props passed down from the CarView component */
    return (
       <div>
           <div className="card">
               <div className="card-image">
                   <img src={image} alt={`${model}`}/>
               </div>
               <div className="card-header">
                   <h1>{model}</h1>
               </div>
               <div className="card-body">
                   <h2>Make: {make}</h2>
                   <p>Seats: {seats}</p>
                   <p>Car ID: {id}</p>
               </div>
           </div>
       </div>
    )
}