/* Import of React hooks need in this component */
import {useEffect, useState} from "react";

/* Import of axios to use for the fetching of data from the backend */
import axios from 'axios';

/* Import of other components needed in this module */
import { CarCard } from "./CarCard";

/* Import of main stylesheet generated by SCSS files and preprocessor */
import '../scss/main.css';

/* The main car view component that shows cards of each car with its details on it */
export const CarView = () => {

    /* Setting of a state for the data request fetched by axios*/
    const [dataRequest, setDataRequest] = useState([]);

    /* The base URL to gain access to the RESTful API */
    const fetchUrl = 'http://localhost:8080/api';

    /* Using the useEffect hook to facilitate the axios call and passing an empty array (i.e., no dependencies
    * as the second argument to ensure there is only one render as a result of the hook. */
    useEffect(() => {
        axios.get(fetchUrl)
            .then((response) => setDataRequest(response.data))
            .catch((error) => console.error(error.message))
    }, []);

    /* The rendering of the cards using the data that was fetched from the server and passing the data on
    * to the CarCards as props */
    return (
        <div className={"card-container"}>
            <div className={"card-wrapper"}>
                {dataRequest.map((car, index) => {
                    return (
                        <div className={"card-wrapper"} key={index}>
                            <CarCard
                                id={car.id}
                                make={car.make}
                                model={car.model}
                                seats={car.seats}
                                image={car.image}
                            />
                        </div>
                    )
                })}
            </div>
        </div>
    )
}