/* Import of main stylesheet generated by SCSS files and preprocessor */
import '../scss/main.css';

/* The LandingPage component which is the first render that a visitor sees. */
export const LandingPage = () => {

    return (
        <div className={"landing-page-wrapper"}>
            <h1>Welcome</h1>
            <h2>Car Database</h2>
            <p>Please use the navigation buttons at the top to interact with this simulated database</p>
        </div>
    )
}