/* Import of main stylesheet generated by SCSS files and preprocessor */
import '../scss/main.css';

/* Import of the useState hook needed in this component */
import {useState} from "react";

/* Import of axios to make a put request to the server to update the relevant information */
import axios from 'axios';

/* The component responsible for modifying or editing information specified by the user via a form */
export const ModifyCar = () => {

    /* The declaration and initialisation of all the state variables used in this component */
    const [carId, setCarId] = useState('');
    const [propertyToUpdate, setPropertyToUpdate] = useState('');
    const [newValue, setNewValue] = useState('');
    const [post, setPost] = useState('');

    /* The base URL used to access the car_api RESTful API */
    const baseURL = 'http://localhost:8080/api';

    /* This event handler callback function handles the processing of user input and then the axios
    * put request to the server to make the necessary edit */
    const submitModificationHandler = (event)  => {
        event.preventDefault();

        let propertyObject = {};
        propertyObject[propertyToUpdate.toLowerCase()] = newValue;

        axios.put(`${baseURL}/${carId}`, propertyObject)
            .then(response => {
                setPost(response.data)
                console.log(JSON.stringify(post));
            })
    }

    /* The rendering of the component in the shape of a form that is needed to take in user input
    * which is passed to the server by the above axios put request */
    return (
        <div className={'modify-cars-form-wrapper'}>
            <form onSubmit={submitModificationHandler}>
                <h1>Modify Car</h1>
                <div className={'form-element'}>
                    <label htmlFor={'carId'}>Car ID</label>
                    <input
                        type="text"
                        id="carId"
                        name="carId"
                        placeholder={"Car ID"}
                        onChange={event => setCarId(event.target.value)}
                    />
                </div>
                <div className={'form-element'}>
                    <label htmlFor={'propToUpdate'}>
                        Property To Update (Make, Model, Seats, Image URL
                    </label>
                    <input
                        type={'text'}
                        id={"PropToUpdate"}
                        name={'propToUpdate'}
                        placeholder={'Property To Update'}
                        onChange={event => setPropertyToUpdate(event.target.value)}
                    />
                </div>
                <div className={'form-element'}>
                    <label htmlFor={'newValue'}>New Value</label>
                    <input
                        type={'text'}
                        id={'newValue'}
                        name={"newValue"}
                        placeholder={'New Value'}
                        onChange={event => setNewValue(event.target.value)}
                    />
                </div>
                <div className={'form-element'}>
                    <button onSubmit={submitModificationHandler}>Submit</button>
                </div>
            </form>
            <div>
                {post && <h1>The entry has been updated</h1>}
            </div>
        </div>
    )
}