/* Import of the Link element from React-Router to enable the routing links in the navbar */
import { Link } from 'react-router-dom';

/* Import of the main stylesheet generated by the SCSS files and preprocessor */
import '../scss/main.css';
/* Import of the Logo used in the navbar */
import CarLogo from '../images/campbell-3ZUsNJhi_Ik-unsplash.png';

/* The Navigation component which is rendered in the App main component and therefore all pages */
export const Navigation = () => {
    return (
        <nav className={"navbar"}>
            {/* Logo */}
            <img className={"navbar-logo"} src={CarLogo} alt={'Car Logo'}/>
            {/* Buttons that link to the various routes */}
            <div className={"navbar-list"}>
                <h1>Car database</h1>
                {/* Using the Link component from React-Router to route to the correct pages specified in App.js */}
                <Link to={'/'}><button className={"navbar-link"}>Home</button></Link>
                <Link to={'/carView'}><button className={"navbar-link"}>View cars</button></Link>
                <Link to={'/addCars'}><button className={"navbar-link"}>Add cars</button></Link>
                <Link to={'/modifyCar'}><button className={"navbar-link"}>Modify cars</button></Link>
                <Link to={'/deleteCar'}><button className={"navbar-link"}>Delete cars</button></Link>
            </div>
        </nav>
    )
}